name: "Rust CI"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  typos-cli:
    name: typos
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        # ensuring the codebases is avalable to the workflow
        uses: actions/checkout@v4

      - name: Install Typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli

      - name: Run typos
        run: typos

